"""
Real exposure surface for the Ethiopia Hazard/Risk Layers Exposure Map.

Replaces the synthetic lat/lon-formula exposure surface previously in
ethiopia_forecast_grid_pipeline.py with a composite of two real, public
datasets, aggregated onto the same 0.5-degree grid the hazard/risk layers
already use:

- WorldPop Ethiopia 2020 population count, 1km (people exposed).
- FAO/Harvard Dataverse Gridded Livestock of the World v4 (2015) cattle,
  sheep, and goats density, 5 arcmin (~10km) (pastoralist livestock
  exposure -- highly relevant to Ethiopia drought risk in Borena, Afar,
  and Somali region, where livestock loss is often the dominant impact
  channel, not just population count).

Raw source rasters live in data/raw/exposure/ (downloaded once, not
regenerated by this script -- see README note in that folder). This module
aggregates them into data/processed/ethiopia_exposure_grid.json, which
ethiopia_forecast_grid_pipeline.py's calculate_exposure() looks up by grid
cell instead of recomputing per run.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import rasterio
from rasterio.transform import rowcol

from app.data_pipeline.ethiopia_forecast_grid_pipeline import (
    EXPOSURE_GRID_PATH,
    GRID_RESOLUTION,
    LAT_MAX,
    LAT_MIN,
    LON_MAX,
    LON_MIN,
    frange,
)

RAW_DIR = Path("data/raw/exposure")
OUTPUT_PATH = EXPOSURE_GRID_PATH

POPULATION_PATH = RAW_DIR / "eth_population_2020_1km.tif"
CATTLE_PATH = RAW_DIR / "global_cattle_2015.tif"
GOATS_PATH = RAW_DIR / "global_goats_2015.tif"
SHEEP_PATH = RAW_DIR / "global_sheep_2015.tif"

# FAO Tropical Livestock Unit (TLU) conversion factors. Cattle, sheep, and
# goats have very different biomass/subsistence value per head, so a raw
# headcount sum would overweight whichever species happens to be most
# numerous. TLU is the standard FAO convention for combining mixed herds
# into one comparable unit (1 cow = 1.0 TLU, 1 sheep/goat = 0.1 TLU).
TLU_FACTORS = {"cattle": 1.0, "sheep": 0.1, "goats": 0.1}


def clamp01(value: float) -> float:
    return max(0.0, min(1.0, value))


def load_count_array(path: Path) -> Tuple[np.ndarray, "rasterio.Affine"]:
    with rasterio.open(path) as src:
        arr = src.read(1, masked=True).astype("float64")
        arr = arr.filled(0.0)
        # Both sources use large-negative sentinels for nodata/ocean/no-count
        # cells; treat those (and any stray negative count) as zero, not a
        # real negative population/animal count.
        arr[arr < 0] = 0.0
        return arr, src.transform


def sum_in_window(arr: np.ndarray, transform, west: float, south: float, east: float, north: float) -> float:
    """Sum all pixels of `arr` whose centers fall within the given lon/lat window."""

    row_start, col_start = rowcol(transform, west, north)
    row_stop, col_stop = rowcol(transform, east, south)

    row_start, row_stop = sorted([row_start, row_stop])
    col_start, col_stop = sorted([col_start, col_stop])

    row_start = max(row_start, 0)
    col_start = max(col_start, 0)
    row_stop = min(row_stop + 1, arr.shape[0])
    col_stop = min(col_stop + 1, arr.shape[1])

    if row_start >= row_stop or col_start >= col_stop:
        return 0.0

    return float(np.nansum(arr[row_start:row_stop, col_start:col_stop]))


def percentile_normalize(
    raw_values: Dict[str, float],
    low_percentile: float = 5.0,
    high_percentile: float = 95.0,
) -> Dict[str, float]:
    """Log-transform, then min-max stretch across the populated cells' own spread.

    Population and livestock counts are both extremely right-skewed (a
    handful of dense urban/grazing cells vs. many near-zero cells outside
    Ethiopia's border within this rectangular grid), AND every 0.5-degree
    cell is large enough (~3,000 km^2) that even a sparsely populated rural
    cell's total headcount is already in the hundreds to low thousands.
    Anchoring the log scale's floor at raw zero (as a naive log1p / max
    would) wastes most of the 0-1 range on the "0 to a few hundred" segment
    that almost no real cell falls into, and compresses every actually
    populated cell into the top of the range regardless of how rural or
    urban it is.

    Instead, stretch log1p(value) linearly between the 5th and 95th
    percentile of the *nonzero* cells -- i.e. across the spread real
    Ethiopian cells actually span -- so a lightly populated rural cell and a
    dense urban one land at meaningfully different points, not both near 1.0.
    Cells outside that spread clamp to 0 or 1. This mirrors the percentile-based
    (p10/p90) color-scaling already used for raster rendering in
    app/api/seasonal_raster_maps.py's get_render_config.
    """

    log_values = {key: math.log1p(max(value, 0.0)) for key, value in raw_values.items()}
    nonzero_logs = [value for key, value in log_values.items() if raw_values[key] > 0]

    if not nonzero_logs:
        return {key: 0.0 for key in raw_values}

    floor = float(np.percentile(nonzero_logs, low_percentile))
    ceiling = float(np.percentile(nonzero_logs, high_percentile))

    if ceiling <= floor:
        return {key: (1.0 if raw_values[key] > 0 else 0.0) for key in raw_values}

    return {key: clamp01((value - floor) / (ceiling - floor)) for key, value in log_values.items()}


def build_exposure_grid() -> Dict[str, Dict]:
    population_arr, population_transform = load_count_array(POPULATION_PATH)
    cattle_arr, cattle_transform = load_count_array(CATTLE_PATH)
    goats_arr, goats_transform = load_count_array(GOATS_PATH)
    sheep_arr, sheep_transform = load_count_array(SHEEP_PATH)

    lats = frange(LAT_MIN, LAT_MAX, GRID_RESOLUTION)
    lons = frange(LON_MIN, LON_MAX, GRID_RESOLUTION)

    raw_population: Dict[str, float] = {}
    raw_livestock: Dict[str, float] = {}

    for lat in lats:
        south, north = lat, round(lat + GRID_RESOLUTION, 6)
        for lon in lons:
            west, east = lon, round(lon + GRID_RESOLUTION, 6)
            lat_center = round(lat + GRID_RESOLUTION / 2.0, 6)
            lon_center = round(lon + GRID_RESOLUTION / 2.0, 6)
            cell_id = f"{lat_center}_{lon_center}"

            raw_population[cell_id] = sum_in_window(population_arr, population_transform, west, south, east, north)

            raw_livestock[cell_id] = (
                TLU_FACTORS["cattle"] * sum_in_window(cattle_arr, cattle_transform, west, south, east, north)
                + TLU_FACTORS["sheep"] * sum_in_window(sheep_arr, sheep_transform, west, south, east, north)
                + TLU_FACTORS["goats"] * sum_in_window(goats_arr, goats_transform, west, south, east, north)
            )

    population_norm = percentile_normalize(raw_population)
    livestock_norm = percentile_normalize(raw_livestock)

    grid: Dict[str, Dict] = {}
    for cell_id in raw_population:
        exposure = round(0.5 * population_norm[cell_id] + 0.5 * livestock_norm[cell_id], 3)
        grid[cell_id] = {
            "population_total": round(raw_population[cell_id], 1),
            "population_norm": round(population_norm[cell_id], 3),
            "livestock_tlu": round(raw_livestock[cell_id], 1),
            "livestock_norm": round(livestock_norm[cell_id], 3),
            "exposure": exposure,
        }

    return grid


def run_exposure_data_pipeline() -> Dict[str, Dict]:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    grid = build_exposure_grid()

    OUTPUT_PATH.write_text(
        json.dumps(
            {
                "metadata": {
                    "title": "Ethiopia Exposure Grid",
                    "sources": [
                        "WorldPop Ethiopia 2020 population count, 1km (data.worldpop.org)",
                        "FAO Gridded Livestock of the World v4 (2015) cattle/sheep/goats, "
                        "5 arcmin (Harvard Dataverse, dataverse.harvard.edu/dataverse/glw_4)",
                    ],
                    "method": (
                        "Population and TLU-weighted livestock headcount summed per 0.5-degree "
                        "grid cell, then log1p + 95th-percentile normalized to 0-1 and combined "
                        "50/50 into `exposure`."
                    ),
                    "resolution_degrees": GRID_RESOLUTION,
                    "cell_count": len(grid),
                },
                "cells": grid,
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    print("Ethiopia exposure data pipeline completed.")
    print(f"Output: {OUTPUT_PATH}")
    print(f"Cells: {len(grid)}")

    return grid


if __name__ == "__main__":
    run_exposure_data_pipeline()
